[build]
builder = "nixpacks"
buildCommand = "DATABASE_URL=file:./dev.db npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma db push && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
